server_version setable as key for dowload_url
Tom01098/terraform-aws-minecraft pull request #3
Opened 2023-01-30 00:51 UTC by bociub

Hello

**main.tf:**
line5: commented out. Is that a right version number?
line94: download urls are in a map. server version is usable as key to fetch the proper download link.

**variables.tf**
download_url became a map where keys are version numbers and values are download links.
server_version is the key to find the right download link.

I was not able to find **official** location to download older version of Minecraft serves.
I bet you know that but ssh access not configured for its security group.
I would like to mention that the server's interface directly connected to the internet which (as I know) is not a good practice, because of security reasons.

b.

2023-01-31 18:04 UTC, Tom01098 requested changes
Hi @bociub, thanks so much for this PR! I really appreciate these changes. I have left a few comments regarding what I think we should change to make this more user-friendly and also allow a user to upgrade their server version to a version we don't currently have in this file.

Happy to discuss further 😄 I'll also release this at `1.1.0` and add a changelog to credit you for the changes if you would like.

2023-01-31 18:04 UTC, Tom01098 commented on main.tf
> +      #version = "~> 4.33"
Must uncomment this line. This means that any `hashicorp/aws` provider version since `4.33.0` is compatible (but not version `5`, as that may be breaking).

You can learn more about version constraints at [their documentation](https://developer.hashicorp.com/terraform/language/expressions/version-constraints).

Did you have any actual issues before uncommenting this? I don't believe there should be any but it's a bug if there is....

2023-01-31 18:04 UTC, Tom01098 commented on variables.tf
> +    "1.19.2" = "next url"
I know that `1.19.2` is available here:
```suggestion
    "1.19.2" = "https://piston-data.mojang.com/v1/objects/f69c284232d7c7580bd89a5a4931c3581eae1378/server.jar"
```
But the rest are a mystery :)

2023-01-31 18:04 UTC, Tom01098 commented on variables.tf
>  variable "download_url" {
This looks on the right track, but I don't think this should be a variable as this is not something we want a user of this to be changing.

Instead, here's my thoughts (feel free to discuss!):

- Move this map to a [local variable](https://developer.hashicorp.com/terraform/tutorials/configuration-language/locals).
- Make `download_url` a string and `server_version` also a string. Both of them default to `null`.
- Write [validations](https://developer.hashicorp.com/terraform/language/values/variables#custom-validation-rules) that only one of them is not null.
- Then when you download the server, use the one that makes sense. You could use a [conditional expression](https://developer.hashicorp.com/terraform/language/expressions/conditionals) for this.

2023-01-31 18:08 UTC, Tom01098 commented
> I bet you know that but ssh access not configured for its security group.
SSH access from EC2 Instance Connect should work if you run this command:
```
terraform apply -var "ec2_instance_connect=true"
```
Does this work for you? I didn't add any way to SSH in from your own terminal because I couldn't figure out how best to set up the keys required. If this is something you want, feel free to create an issue!

2023-01-31 18:09 UTC, Tom01098 commented
> I would like to mention that the server's interface directly connected to the internet which (as I know) is not a good practice, because of security reasons.
This is correct, it's currently a publicly-accessible server. I might create an issue to restrict this to a known set of IPs.

2023-01-31 18:10 UTC, Tom01098 commented
Fixes #2.

2023-02-01 20:08 UTC, bociub commented on main.tf
> +      #version = "~> 4.33"
Hi
Couple days ago I was not able to apply the code, because of that line, however it is working now properly.

2023-02-01 20:34 UTC, bociub commented on variables.tf
> +    "1.19.2" = "next url"
Hi 
There are many unofficial sources on the google. I am not able to judge to what extent they are reliable. To be honest I never played minecraft and I am not intended to do so. I do not understand what the benefit is of using older versions.
Have you seen this one: https://hub.docker.com/r/itzg/minecraft-server ?
Aslo an open question where the user's data is going to be stored, for example what is in their bag.

B.

2023-02-01 21:04 UTC, bociub commented on variables.tf
>  variable "download_url" {
I have a big question: how are you intended to create a user interface and how that interface will pass its attributes to the terraform code? If it is going to run locally the (i believe that) easiest way is using .tfvars so the variables.tf is going to declare what kind of variables are in use and .tfvars gives value for them. way more easier to write the latter one from a user interface.

2023-02-01 21:07 UTC, bociub commented
SSH: You need to configure a keypair on amazon manually. I know only this approach.

Before the end of the weekend i am intended to update the code with : ssh access, putting the server onto vpc, (using tfvars,) using terraform cloud as back-end and handling secrets there. 

What kind of user interface is in your imagination?

2023-02-03 22:58 UTC, bociub commented
closing

2023-02-03 22:58 UTC, closed without merging